FROM node:16.13.1-alpine3.14

# Set the Node environment to development or production to ensure all packages are installed
ENV NODE_ENV development

WORKDIR /usr/src/app
RUN rm -rf /usr/src/app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "yarn.lock", "./"]

RUN yarn
COPY . .

RUN yarn build

# Expose port 3000 for the SvelteKit app and 24678 for Vite's HMR
EXPOSE 24678
EXPOSE 3000

CMD ["yarn", "dev", "--host", "0.0.0.0"]
# CMD ["yarn", "preview", "--host", "0.0.0.0"]